CREATE TABLE ORDERS (
    ID BIGINT PRIMARY KEY,
    SELLER_DNI VARCHAR(255),
    BUYER_DNI VARCHAR(255),
    JAVA_COINS_AMOUNT BIGINT,
    USD_AMOUNT BIGINT,
    JAVA_COIN_PRICE BIGINT,
    BANK_ACCEPTED VARCHAR(255),
    WALLET_ACCEPTED VARCHAR(255),
    ORDER_STATE VARCHAR(255)
);
